name: passion dedication inspiration
favicon: null
layout_spectrum: 1
typography_spectrum: 0.96817
title: PASSION + DEDICATION + INSPIRATION
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f2'
    - '#cdcdcd'
    - '#121212'
    - '#9b9b9b'
    - '#414141'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.6189238068182021
purpose: []
