name: passion dedication inspiration
favicon: null
layout_spectrum: 0.24955
typography_spectrum: 0.84776
title: PASSION + DEDICATION + INSPIRATION
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2F2F2'
    - '#CFCFCF'
    - '#151515'
    - '#777777'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.9375
  rhythmicContrast: 0.6189238068182021
purpose: []
