name: passion dedication inspiration
favicon: null
layout_spectrum: 0.8684633639641106
typography_spectrum: 0.5105930992867798
title: PASSION + DEDICATION + INSPIRATION
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2459009811282158
  lightness: 0.38875782466493547
  saturation: 0.6638502206187695
  rhythmicContrast: 0.6189238068182021
purpose: []
